[agent]
  collection_jitter = "0s"
  debug = false
  flush_interval = "10s"
  flush_jitter = "0s"
  hostname = ""
  interval = "10s"
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  omit_hostname = false
  precision = ""
  round_interval = true

[[outputs.file]]
  files = ["/var/log/telegraf/out.log"]

[[outputs.influxdb_v2]]
  bucket = "lab"
  organization = "lab"
  token = "{{ telegraf_secrets.json.data.data.influxdb_token }}"
  urls = ["http://10.0.3.2:8086"]

[[inputs.syslog]]
  best_effort = true
  server = "tcp://:6514"
