[poller]
  debug = true
  quiet = false
  plugins = []

[prometheus]
  disable = false
  http_listen = "0.0.0.0:9130"
  ssl_cert_path = ""
  ssl_key_path  = ""
  report_errors = true
  dead_ports = false

#### OUTPUTS

[influxdb]
  disable = false
  url  = "http://10.0.3.2:8086"
  user = "{{ unpoller_secrets.json.data.data.influxdb_user }}"
  pass = "{{ unpoller_secrets.json.data.data.influxdb_pass }}"
  db = "lab"
  verify_ssl = false
  interval = "30s"
  dead_ports = false

[loki]
  disable = true
  url = ""
  user       = ""
  pass       = ""
  verify_ssl = false
  tenant_id  = ""
  interval   = "2m"
  timeout    = "10s"

[webserver]
  enable = false
  port   = 37288
  html_path     = "/usr/local/lib/unpoller/web"
  ssl_cert_path = ""
  ssl_key_path  = ""
  max_events = 200

#### INPUTS

[unifi]
  dynamic = false

[unifi.defaults]
  url = "https://10.0.1.1"
  user = "grafana"
  pass = "Grafana12345!"
  sites = ["all"]
  save_sites = true
  hash_pii = false
  save_ids = false
  save_events = false
  save_alarms = false
  save_anomalies = false
  save_dpi = false
  save_rogue = false
  verify_ssl = false
  ssl_cert_paths = []
